routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();


//Admin Panel
Route::group([
    'prefix' => 'dashboard'
    ], function () {
        Route::get('login', 'HomeController@dashboardLogin')->middleware('guest')->name('dashboard.login');
        Route::get('/', 'HomeController@dashboard')->name('dashboard');
        Route::get('{any}', 'HomeController@dashboard')->where('any', '.*');
});
// End Admin Panel

//  Helper Controller Routes
// Route::get('test', 'HelperController@test')->name('test');

Route::get('setlocale/{locale}', 'HelperController@locale')->name('locale');

Route::get('slugify', 'HelperController@slugify')->name('slugify');

Route::post('upload/image', 'HelperController@uploadImage')->name('upload.image');

Route::get('world/countries', 'HelperController@worldCountries')->name('world.countries');

Route::get('roles', 'HelperController@roles')->name('roles.index');
Route::get('locales', 'HelperController@locales')->name('locales.index');

// End Helper Controller Routes

//Customer Routes
Route::get('profile', 'CustomerController@show')->name('profile');
Route::get('profile/edit', 'CustomerController@edit')->name('profile.edit');
Route::put('profile', 'CustomerController@update')->name('profile.update');
// End Customer Routes

//Day Extra Routes
Route::post('{tour}/day/groupsave', 'DayController@massiveSave' )->name('day.massive');
Route::post('day/{day}/mail', 'DayController@mail' )->name('day.mail');
// End Day Extra Routes

//Location Extra Routes
Route::get('country', 'LocationController@indexCountries')->name('country.index');
// End Location Extra Routes

//Reservation Extra Routes
Route::get('preview/{tour}', 'ReservationController@showPreview')->name('reservation.preview');

Route::post('reservation/{tour}', 'ReservationController@store')->name('reservation.pay');
Route::post('tour/{tour}/book', 'ReservationController@book')->name('tour.book');

Route::delete('day/{day}/cancel', 'ReservationController@cancel')->name('day.cancel');
Route::delete('{reservation}/refund/', 'ReservationController@refund')->name('reservation.refund');
//End Reservation Extra Routes

//User Extra Routes
Route::get('guide', 'UserController@indexGuides')->name('guide.index');
Route::get('me', 'UserController@showMe')->name('user.me');
//End User Extra Routes

//Tour Extra Routes
Route::get('tour/search', 'TourController@search')->name('search');
Route::get('tour/{tour}/translate', 'TourController@translate')->name('tour.translate');

Route::post('tour/{tour}/translate', 'TourController@saveTranslate')->name('tour.savetranslate');
Route::post('tour/{tour}/activate', 'TourController@activate')->name('tour.activate');
Route::post('tour/{tour}/deactivate', 'TourController@deactivate')->name('tour.deactivate');
//End Tour Extra Routes


/**
 * Resourcefull-ish routes group by controller/resource
 */
//Resource Routes
// Route::resource('rating', 'RatingController');

//End Resource Routes

// ApiResource Routes
Route::apiResources([
    'day' => 'DayController',
    'day-time' => 'DayTimeController',
    'feature' => 'FeatureController',
    'grouptype' => 'GroupTypeController',
    'location' => 'LocationController',
    'point' => 'PointController',
    'tag' => 'TagController',
    'user' => 'UserController',
    'tour' => 'TourController',
]);

Route::apiResource('reservation','ReservationController')->except([
    'store', 'update'
]);
//End ApiResource Routes

resources/views/frontend/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>
        <!-- Favicon -->
        <link rel="icon" type="image/png" href="assets/images/favicon.png">

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


        <!-- Seo meta tags for Search Engine Optimization -->
        <meta name="author" content="Myself">
        <meta name="description" content="  Welcome to Bakanto My Tour, we got the best tours and amazing places waiting for you!">
        <meta name="keywords" content="travel agency, tour agency, travel, adventure, destinations">
        <!-- Stylesheets -->
        <link href="{{ asset('img/brand/favicon.png') }}" rel="icon" type="image/png">
        <link href="{{ asset('vendor/nucleo/css/nucleo.css')}}" rel="stylesheet">
        <link href="{{ asset('vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
        <link href="{{ asset('css/theme.css') }}" rel="stylesheet">
    </head>

   <body>
    <!-- navbar -->
    @include('frontend.layouts.nav')
    <!-- /navbar -->

    {{-- @yield('hero') --}}

    @includeWhen($errors->any() , 'frontend.shared.errors')
    @includeWhen( session()->has('success'), 'frontend.shared.success')
    @includeWhen( session()->has('warning'), 'frontend.shared.warning')

    @yield('content')
     
        <!-- Footer -->
        @include('frontend.layouts.footer')
        <!-- End of Footer -->
        <script  src="{{ asset('js/theme.js') }}" ></script>
        @yield('scripts')
    </body>
</html> 

resources/views/frontend/layouts/footer.blade.php
<footer class="footer">
    <div class="container">
        <div class="row row-grid align-items-center mb-5">
            <div class="col-lg-6">
                <ul class="list-unstyled quick-links">
                    <li>Contact Us</li>
                    <li>
                        <p class="white light">Have Questions? Our team is ready to help you!</p>
                    </li>
                    <li>
                        <h6><i class="fa fa-map-marker mr-2"></i>Madrid, Spain</h6>
                    </li>
                    <li>
                        <h6><i class="fa fa-phone-square mr-2"></i>Spain (+34) 3333.1111</h6>
                    </li>
                    <li>
                        <h6><i class="fa fa-envelope mr-2"></i>info@bakanto.com</h6>
                    </li>
                </ul>
            </div>
            <div class="col-lg-6 text-lg-right btn-wrapper">
                <a target="_blank" href="#" class="btn btn-neutral btn-icon-only btn-twitter btn-round btn-lg"
                    data-toggle="tooltip" data-original-title="Follow us">
                    <i class="fa fa-twitter"></i>
                </a>
                <a target="_blank" href="#" class="btn btn-neutral btn-icon-only btn-facebook btn-round btn-lg"
                    data-toggle="tooltip" data-original-title="Like us">
                    <i class="fa fa-facebook-square"></i>
                </a>
            </div>
        </div>
        <hr>
        <div class="row align-items-center justify-content-md-between">
            <div class="col-md-6">
                <div class="copyright">
                    &copy; 2018
                    <a href="#" target="_blank">Bakanto</a>.
                </div>
            </div>
            <div class="col-md-6">
                <ul class="nav nav-footer justify-content-end">
                    <li class="nav-item">
                        <a href="#" class="nav-link" target="_blank">Privacy Policy</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link" target="_blank">Terms Of Service</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link" target="_blank">FAQs</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

resources/views/frontend/layouts/nav.blade.php
<header class="header-global">
    <nav id="navbar-main" class="navbar navbar-expand-lg navbar-transparent ">
      <div class="container">
        <a class="navbar-brand mr-lg-5" href="{{route('home')}}">
          <img src="/img/brand/logo-bakanto-white.png">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="navbar_global">
          <div class="navbar-collapse-header">
            <div class="row">
              <div class="col-6 collapse-brand">
                <a href="{{route('home')}}">
                  <img src="/img/brand/blue.png">
                </a>
              </div>
              <div class="col-6 collapse-close">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                  <span></span>
                  <span></span>
                </button>
              </div>
            </div>
          </div>
          <ul class="navbar-nav navbar-nav-hover ml-lg-auto">
              <li class="nav-item">
              <a class="nav-link nav-link-icon" href="{{route('tour.index')}}">
                      <span class="nav-link-inner--text">Tours</span>
                  </a>
              </li>
            @guest
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
            </li>
            @else
            @if (auth()->user()->hasRole('Customer'))
                        <li class="nav-item dropdown   mr-3 my-lg-0 my-2 ml-lg-0 ml-3">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ auth()->user()->name }} <span class="caret"></span>
                                    </a>
                                    
                               <div class="dropdown-menu  mr-3 my-lg-0 my-2 ml-lg-0 ml-3" aria-labelledby="navbarDropdown">
                            <a  class="dropdown-item text-center"  href="{{ route('profile') }}">{{ __('Profile') }}</a>

                            @if (auth()->user()->getReservedTours()->count() > 0)
                            <a  class="dropdown-item text-center"  href="{{ route('reservation.index') }}">{{ __('Reservations') }}</a>
                            @endif

                            <a class="dropdown-item text-center" href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                          document.getElementById('logout-form').submit();">
                             {{ __('Logout') }}
                         </a>

                         <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                             @csrf
                         </form>
                        </div>
                        </li>
                        @else
                            <li class="nav-item dropdown   mr-3 my-lg-0 my-2 ml-lg-0 ml-3">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ auth()->user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu  mr-3 my-lg-0 my-2 ml-lg-0 ml-3" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item text-center" href="{{ route('dashboard') }}">{{__('common.Dashboard')}}</a>
                                     <div class="dropdown-divider"></div>
                                    <a class="dropdown-item text-center" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            @endif
                        @endguest
            
            <li class="nav-item dropdown ">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false" v-pre> <i class="fa fa-globe"></i>  <span class="caret"></span>
                </a>

                <div class="dropdown-menu  mr-3 my-lg-0 my-2 ml-lg-0 ml-3" aria-labelledby="navbarDropdown">
                    @foreach (config()->get('app.locales') as $locale)
                    <a class="dropdown-item text-center" href="{{ route('locale',$locale) }}">
                        {{strtoupper($locale)}}</a>
                    <div class="dropdown-divider"></div>
                    @endforeach
                
                </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

resources/views/frontend/layouts/sidebar.blade.php
<div class="list-group" style="display: none;">
    <span class="list-group-item active">
        <img class="svgcenter mt-4 logo-light" src="/img/brand/logo_white.png" alt="image">
        <span class="pull-right" id="slide-submenu">
            <i class="fa fa-times"></i>
        </span>
    </span>
<h6 class="white py-4 px-5 text-center  list-group-item light">“{{__('common.Real guides for the price of a free tour')}}”</h6>
    <p class="white py-4 px-5 text-center  list-group-item light">
        {{__('common.Welcome to Bakanto My Tour, we got the best tours and amazing places waiting for you!')}}
    </p>
    <ul class="list-group-item py-4">
        <li>
            <h5 class="white text-center"><i class="white fas fa-map-marker-alt mr-2"></i>
                {{__('common.Avenue')}}, Madrid</h5>
        </li>
        <li>
            <h5 class="white text-center"><i class="white fas fa-phone-square mr-2"></i>Madrid, {{__('common.Spain')}} (+1) 3333.1111</h5>
        </li>
        <li>
            <h5 class="white text-center"><i class="white fas fa-envelope mr-2"></i>info@bakanto.com</h5>
        </li>
    </ul>
    <div class="list-group-item text-center pt-4 ">
    <h6>{{__('common.Follow Us')}}</h6>
        <ul class="text-center py-3">
            <li class="list-inline-item"><a href="http://www.facebook.com/bakantoMyTour/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
            <li class="list-inline-item"><a href="http://www.twitter.com/bakantomytour/" target="_blank"><i class="fab fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="http://www.instagram.com/bakantomytour/" target="_blank"><i class="fab fa-instagram"></i></a></li>
        </ul>
        <div class="list-group-item py-4">
            <a href="/site/aboutus" class="d-block white py-2">
                <i class="fa fa-users"></i> {{__('common.About Us')}}
            </a>
            <a class="white d-block" href="/site/contact-us">
                <i class="fa fa-envelope"></i>{{__('common. Contact Us')}}
            </a>
        </div>
    </div>
</div>