routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();


//Admin Panel
Route::group([
    'prefix' => 'dashboard'
    ], function () {
        Route::get('login', 'HomeController@dashboardLogin')->middleware('guest')->name('dashboard.login');
        Route::get('/', 'HomeController@dashboard')->name('dashboard');
        Route::get('{any}', 'HomeController@dashboard')->where('any', '.*');
});
// End Admin Panel

//  Helper Controller Routes
// Route::get('test', 'HelperController@test')->name('test');

Route::get('setlocale/{locale}', 'HelperController@locale')->name('locale');

Route::get('slugify', 'HelperController@slugify')->name('slugify');

Route::post('upload/image', 'HelperController@uploadImage')->name('upload.image');

Route::get('world/countries', 'HelperController@worldCountries')->name('world.countries');

Route::get('roles', 'HelperController@roles')->name('roles.index');
Route::get('locales', 'HelperController@locales')->name('locales.index');

// End Helper Controller Routes

//Customer Routes
Route::get('profile', 'CustomerController@show')->name('profile');
Route::get('profile/edit', 'CustomerController@edit')->name('profile.edit');
Route::put('profile', 'CustomerController@update')->name('profile.update');
// End Customer Routes

//Day Extra Routes
Route::post('{tour}/day/groupsave', 'DayController@massiveSave' )->name('day.massive');
Route::post('day/{day}/mail', 'DayController@mail' )->name('day.mail');
// End Day Extra Routes

//Location Extra Routes
Route::get('country', 'LocationController@indexCountries')->name('country.index');
// End Location Extra Routes

//Reservation Extra Routes
Route::get('preview/{tour}', 'ReservationController@showPreview')->name('reservation.preview');

Route::post('reservation/{tour}', 'ReservationController@store')->name('reservation.pay');
Route::post('tour/{tour}/book', 'ReservationController@book')->name('tour.book');

Route::delete('day/{day}/cancel', 'ReservationController@cancel')->name('day.cancel');
Route::delete('{reservation}/refund/', 'ReservationController@refund')->name('reservation.refund');
//End Reservation Extra Routes

//User Extra Routes
Route::get('guide', 'UserController@indexGuides')->name('guide.index');
Route::get('me', 'UserController@showMe')->name('user.me');
//End User Extra Routes

//Tour Extra Routes
Route::get('tour/search', 'TourController@search')->name('search');
Route::get('tour/{tour}/translate', 'TourController@translate')->name('tour.translate');

Route::post('tour/{tour}/translate', 'TourController@saveTranslate')->name('tour.savetranslate');
Route::post('tour/{tour}/activate', 'TourController@activate')->name('tour.activate');
Route::post('tour/{tour}/deactivate', 'TourController@deactivate')->name('tour.deactivate');
//End Tour Extra Routes


/**
 * Resourcefull-ish routes group by controller/resource
 */
//Resource Routes
// Route::resource('rating', 'RatingController');

//End Resource Routes

// ApiResource Routes
Route::apiResources([
    'day' => 'DayController',
    'day-time' => 'DayTimeController',
    'feature' => 'FeatureController',
    'grouptype' => 'GroupTypeController',
    'location' => 'LocationController',
    'point' => 'PointController',
    'tag' => 'TagController',
    'user' => 'UserController',
    'tour' => 'TourController',
]);

Route::apiResource('reservation','ReservationController')->except([
    'store', 'update'
]);
//End ApiResource Routes

app/Models/Reservation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\{Model, SoftDeletes};

use App\Helpers\Traits\CarbonDate;
use App\Models\{Day, Tour, Extra, UserGuide as Guide, DayTime};
use App\User;
class Reservation extends Model
{
    use SoftDeletes, CarbonDate;

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * @var array
     * Always preload this relationshops
     */
    protected $with = ['day', 'user','day_time'];

    /**
     * @var array
     */
    protected $guarded = [];
    
    /**
     * The client of this reservation
     * @return \App\User
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * The reservation of this reservation
     * @return \App\Models\Day
     */
    public function day()
    {
        return $this->belongsTo(Day::class);
    }

    /**
     * Get this reservation tour
     * @return \App\Models\Tour
     */
    public function tour()
    {
        return $this->belongsTo(Tour::class);
    }

    /**
     * Get this reservation extras
     * @return \App\Models\Extra
     */
    public function extras()
    {
        return $this->hasMany(Extra::class);
    }

    /**
     * Get this reservation day_time
     * @return \App\Models\DayTime
     */
    public function day_time()
    {
        return $this->belongsTo(DayTime::class);
    }

    /**
     * Get the route key for the model
     * @return bool
     */
    public function getRouteKey()
    {
        return $this->stripe_transaction_id;
    }

}

app/Models/Tour.php
<?php

namespace App\Models;

use App\Models\{Location, Feature, GroupType, Rating, Tag, Reservation, Day, Point, DayTime};
use App\User;

use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class Tour extends Model
{
    use HasTranslations;
    
    /**
     * @var array
     */
    protected $guarded = [];

    /**
     * @var array
     * The attributes translatable
     */
    public $translatable = ['name','alias','description','excerpt'];

    /**
     * The castings needed for this model
     * @var array
     */
    protected $casts = [
        'active_days' => 'array',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['not_features', 'features'];

    /**
     * The ratings of this tour
     * @return App\Models\Rating
     */
    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }

    /**
     * Get the route key for the model
     *
     * @return string
     */
    public function getRouteKey()
    {
        return $this->alias;
    }

    /**
     * Get the average ratings for this post
     * @return int
     */
    public function getAverageRating(): int
    {
        return $this->ratings->avg->rating;
    }

    /**
     * The group type this tour belongs to
     * @return App\Models\GroupType
     */
    public function group_types()
    {
        return $this->belongsToMany(GroupType::class);
    }

    /**
     * The tags in this tour
     * @return App\Models\Tag
     */
    public function tags()
    {
        return $this->morphToMany(Tag::class, 'taggable');
    }

    /**
     * The features this tour include
     * @return App\Models\Feature
     */
    public function features()
    {
        return $this->belongsToMany(Feature::class)
            ->withPivot('status');
    }

    /**
     * The location this tour belongs to
     * @return App\Models\Location
     */
    public function location()
    {
        return $this->belongsTo(Location::class);
    }

    /**
     * Get the featured image with the correct path
     *
     * @param string $val Featured Image path
     * @return string
     */
    public function getFeaturedImgAttribute($val)
    {
        if (is_null($val)) {
            return '/img/404.jpg';
        }

        return '/storage/' . $val;
    }

    /**
     * Get the features that this tour does not include
     *
     * @return App\Models\Feature
     */
    public function getNotFeaturesAttribute()
    {
        return $this->features()->wherePivot('status', 0)->get();
    }

    /**
     * Get the features that this tour does not include
     *
     * @return App\Models\Feature
     */
    public function getFeaturesAttribute()
    {
        return $this->features()->wherePivot('status', 1)->get();
    }

    /**
     * Get this tour day_times
     * @return \App\Models\DayTime
     */
    public function day_times()
    {
        return $this->belongsToMany(DayTime::class);
    }

    /**
     * Get the active days in number form --- 0-6 
     * @return array
     */
    public function getDaysNumbers()
    {
        return array_map(function($value){
            switch( strtolower($value) ){
                case 'sunday':
                $val = 0;
                break;
                case 'monday':
                $val = 1;
                break;
                case 'tuesday':
                $val = 2;
                break;
                case 'wednesday':
                $val = 3;
                break;
                case 'thursday':
                $val = 4;
                break;
                case 'friday':
                $val = 5;
                break;
                case 'saturday':
                $val = 6;
                break;
                default:
                $val = null;
                break;
            }
            return $val;
        }, $this->active_days);
    }

    /**
     * Get this tour days 
     * @return \App\Models\Day
     */
    public function days()
    {
        return $this->hasMany(Day::class);
    }

    /**
     * Get this tour days  (reservations)
     * @return \App\Models\Reservation
     */
    public function reservations()
    {
        return $this->hasMany(Reservation::class);
    }

    /**
     * The points in this tour
     * @return App\Models\Point
     */
    public function points()
    {
        return $this->belongsToMany(Point::class)
                    ->withPivot('order');
    }

    /**
     * Get this tours in order
     *
     * @return App\Models\Point
     */
    public function getPointsAttribute()
    {
        return $this->points()->get()->sortBy('pivot.order');
    }

    /**
     * Try to deactivate this tour
     * @return bool true if the tour is deactivate succesfully
     */
    public function deactivate()
    {
        if( ! $this->reservations->isEmpty() ){
            foreach( $this->reservations as $reservation){
                if ( !$reservation->isDeleteable() ){
                    return false;
                }
            }
        }
        $this->status = 0;
        $this->save();
        return true;
    }

    /**
     * Scope a query to only include active tours users.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }

}

resources/views/frontend/reservation/index.blade.php
@extends('frontend.layouts.app')

@section('content')
<section class="section section-md section-shaped">
    <div class="shape bakanto-shape-home" style="background-image: url('http://bakanto.com/img/aboutus3.jpg'); background-position: bottom center;"></div>
    <div class="container shape-container d-flex align-items-center py-md">
        <div class="col px-0">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-8 text-center">
                    <p class="text-white bakanto-text-home">Reservations</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section">
    <div class="container">
                <div class="row justify-content-center">
                    @forelse (auth()->user()->reservations()->withTrashed()->get() as $reservation)
                    <div class="col-md-7 p-2 my-3">
                    <div class="card">
                        <div class="card-header text-white bg-primary  ">
                            <h6 class="text-left">{{__('Reservation')}} {{$reservation->stripe_transaction_id}} 
                            @if($reservation->trashed())<span class="float-right badge badge-pill badge-danger ">{{__('Cancelled')}}</span> @endif</h6>   
                                
                        </div>
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-md-6">
                                        <p>
                                            Date: <strong>{{$reservation->getDateString()}}</strong> <br> 
                                            In the <strong>{{$reservation->day_time->name}}</strong>
                                            for <strong>{{$reservation->persons}} person(s)</strong>
                                        </p>
                                </div>
                                <div class="col-md-6">
                                        <p>
                                            Total ${{$reservation->price}} (USD) <br>
                                            Method: {{$reservation->pay_method}} <br>
                                        </p>
                                </div>
                            </div>
                            <a class="btn float-right text-center btn-outline-primary" href="{{route('reservation.show', $reservation)}}">Check details.</a>
                        </div>
                    </div>
                    </div>
                @empty
                        
                    @endforelse
                </div>
    </div>
</section>

@endsection

resources/views/frontend/reservation/preview.blade.php
@extends('frontend.layouts.app')

@section('content')
<section class="section section-md section-shaped">
    <div class="shape bakanto-shape-home" style="background-image: url('http://bakanto.com/img/aboutus3.jpg'); background-position: bottom center;"></div>
    <div class="container shape-container d-flex align-items-center py-md">
        <div class="col px-0">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-8 text-center">
                    <p class="text-white bakanto-text-home">BOOK YOUR TOUR</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="section ">
    <div class="container">
       <div class="row" >
            <form style="justify-content:center" id="form" action="{{route('reservation.pay', request()->route('tour') )}}" method="POST" class="row">
                    @csrf

           <div class="col-8">
                <div class="card   shadow border-0">
                        <div class="card-body">
                                <div class="row">
                                        {{-- @if ( session()->has(['date', 'day_time', 'persons', 'price']) ) --}}
                                      <h5 class="text-center col-12 mb-3" style="margin:0 auto">  Reservation due {{ session('date')}}  in the {{ session('day_time') }}  <br>
                                            Include's  {{ session('persons')}} persons <br>
                                            Total price: {{ session('price') }} $ (USD) </h5>

                                            @if (session('persons') > 1)
                                                    @for ($i = 0; $i < session('persons') - 1; $i++)
                                                    <div class="col-md-4 mt-2">
                                                        <input class="form-control" type="text" name="extras_name[]" value="{{old('extras_name.' . $i)}}" id="extra_name_{{$i}}" required placeholder="Acompanion #{{$i+1}} name"  >
                                                    </div>
                                                    <div class="col-md-4 mt-2">
                                                    <input class="form-control" type="text" name="extras_email[]" value="{{old('extras_email.' . $i)}}" id="extra_email_{{$i}}" required placeholder="Acompanion #{{$i+1}} email"  >
                                                    </div>
                                                    <div class="col-md-4 mt-2">
                                                    <input class="form-control" type="number" name="extras_age[]" value="{{old('extras_age.' . $i)}}" id="extra_age_{{$i}}" min="1" max="100" required placeholder="Acompanion #{{$i+1}} age"  >
                                                    </div>
                                                @endfor
                                            @endif

                                            <div class="col-12 mt-3">
                                            <textarea name="comment" class="form-control" placeholder="Any extra comments?">{{old('comment')}}</textarea>
                                            </div>
                                            <div class="col-12 mt-3">
                                              <p>
                                                    I've read and understood the <a href="#">Terms and Services</a> 
                                              <input type="checkbox" checked="{{old('terms')}}" name="terms">
                                              </p>
                                                    </div>


                                                    
                                </div>
                        </div>
                    </div>
                    
                    <div class="card  shadow-lg mt-4 border-0">
                        <div class="card-body row">
                                
                    
                            <div class="col-12">
                                <label for="card-element">
                                    Credit or debit card
                                  </label>
                                  <div id="card-element">
                                    <!-- A Stripe Element will be inserted here. -->
                                  </div>
                              
                                  <!-- Used to display form errors. -->
                                  <div id="card-errors" role="alert"></div>
                            </div>
                                
                        </div>
                    </div>
           </div>


           <div class="col-4">
            <div class="card card-lift--hover shadow border-0">
                <img src="{{$tour->featured_img}}" class="card-img-top bakanto-img-top">
                    <div class="card-body py-3">
                    <h5 class="text-uppercase">{{$tour->name}}</h5>
                    <p>{{$tour->excerpt}}</p>
                    <p><strong>from {{$tour->price}}€</strong> <small class="text-muted">per person</small></p>
                        <div>
                            @foreach ($tour->tags as $tag)
                            <span class="badge badge-pill badge-warning">{{$tag->name}}</span>
                            @endforeach
                        </div>
                    <a href="{{route('tour.show',$tour)}}" class="btn btn-warning btn-block mt-4">Learn more</a>
                    </div>
                </div>
       </div>


           
          <div class="col-12 mt-3">
                <a href="{{session()->previousUrl()}}" class="btn btn-outline">Go back.</a>
                <button type="submit" class="btn btn-primary float-right">Ready?</button>
                {{-- @else
                Something has gone wrong, please go back and try again later <a href="{{session()->previousUrl()}}">Go back</a>            
                @endif --}}
          </div>
        </form>    

       </div>
       
    </div>
</section>

@endsection

@section('scripts')
<script src="https://js.stripe.com/v3/"></script>
    <script>
    // Create a Stripe client.
var stripe = Stripe("{{env('STRIPE_KEY')}}");

// Create an instance of Elements.
var elements = stripe.elements({
    locale: '{{app()->getLocale()}}'
});

// Custom styling can be passed to options when creating an Element.
// (Note that this demo uses a wider set of styles than the guide below.)
var style = {
  base: {
    color: '#32325d',
    lineHeight: '18px',
    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
    fontSmoothing: 'antialiased',
    fontSize: '16px',
    '::placeholder': {
      color: '#aab7c4'
    }
  },
  invalid: {
    color: '#fa755a',
    iconColor: '#fa755a'
  }
};

// Create an instance of the card Element.
var card = elements.create('card', {style: style});

// Add an instance of the card Element into the `card-element` <div>.
card.mount('#card-element');

// Handle real-time validation errors from the card Element.
card.addEventListener('change', function(event) {
  var displayError = document.getElementById('card-errors');
  if (event.error) {
    displayError.textContent = event.error.message;
  } else {
    displayError.textContent = '';
  }
});

// Handle form submission.
var form = document.getElementById('form');
form.addEventListener('submit', function(event) {
  event.preventDefault();

  stripe.createToken(card).then(function(result) {
    if (result.error) {
      // Inform the user if there was an error.
      var errorElement = document.getElementById('card-errors');
      errorElement.textContent = result.error.message;
    } else {
      // Send the token to your server.
      stripeTokenHandler(result.token);
    }
  });
});

// Submit the form with the token ID.
function stripeTokenHandler(token) {
  // Insert the token ID into the form so it gets submitted to the server
  var form = document.getElementById('form');
  var hiddenInput = document.createElement('input');
  hiddenInput.setAttribute('type', 'hidden');
  hiddenInput.setAttribute('name', 'stripeToken');
  hiddenInput.setAttribute('value', token.id);
  form.appendChild(hiddenInput);

  // Submit the form
  form.submit();
}</script>
@endsection

resources/views/frontend/reservation/show.blade.php
@extends('frontend.layouts.app')

@section('content')
<section class="section section-md section-shaped">
        <div class="shape bakanto-shape-home" style="background-image: url('http://bakanto.com/img/aboutus3.jpg'); background-position: bottom center;"></div>
        <div class="container shape-container d-flex align-items-center py-md">
            <div class="col px-0">
                <div class="row align-items-center justify-content-center"> 
                    <div class="col-lg-8 text-center">
                        <p class="text-white bakanto-text-home">Reservation #{{$reservation->stripe_transaction_id}}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
<section class="section">
    <div class="container">
        @if ($reservation->trashed())
        <div class="alert alert-danger text-center">
        <h5>{{__('This reservation has been cancelled and refunded!')}}</h5>
        </div>
        @endif        
        <div class="row" style="justify-content:center">
            <div class="col-md-8">
                <div class="card shadow mb-2">
                <div class="card-header bg-primary border-0">
                        <h3 class="text-center">{{__('common.Reservation')}} {{$reservation->stripe_transaction_id}}!</h3>
                </div>
                <div class="card-body ">
                        <div class="row justify-content-center">
                                <div class="col-md-6">
                                        <p class="text-left">
                                                {{$reservation->user->name}}, {{__('you have been emailed the details at')}} <strong>{{$reservation->user->email}}</strong>
                                                
                                        <p>
                                </div>
                                <div class="col-md-6">
                                        <p>
                                                Your reservation for {{$reservation->getDateString()}} <br> 
                                                at the {{$reservation->day_time->name}}
                                                for {{$reservation->persons}} person(s) has been succesfully payed
                                        </p>
                                </div>
                                        
                                <div class="col-md-6">
                                        <p>
                                                {{__('Transaction details:')}} <br>
                                                {{__('Payed')}} ${{$reservation->price}} (USD) <br>
                                                {{__('Method: ')}} {{$reservation->pay_method}} <br>
                                                @if ($reservation->trashed())
                                                    {{__('This reservation has been refunded on the')}} <strong>{{$reservation->deleted_at->toDayDateTimeString()}}</strong> <br>
                                                    {{__('You have been emailed the details ')}}
                                                @endif
                                        </p>
                                </div>
                                <div class="col-md-6">
                                        <p>
                                                {{__('Extra comments')}}: {{$reservation->comment}}
                                        </p>
                                </div>
                                 @if (!$reservation->extras->isEmpty())
                                 <div class="col-md-7 text-center p-2">
                                        <h6>{{__('Accompanions')}}:</h6>
                                       <ul>
                                               @foreach ($reservation->extras as $extra)
                                                   <li>{{$extra->name}} / {{$extra->email}} / {{$extra->age}} </li>
                                               @endforeach
                                       </ul>
                               </div>
                                 @endif
                        </div>
                </div>
                </div>
            </div>
            <div class="col-8 mt-2">
            <a href="{{route('tour.show', $reservation->tour )}}" class="btn btn-primary float-right">{{__('View Tour')}}</a>
            </div>
        </div>

    </div>
</section>

@endsection